### ISSUE TITLE
Reconnection when internet goes off suddenly and comes back

### ISSUE THREAD

**Issue by dhavalocked** [blikoon/Rooster#1]
when internet goes off and comes back suddenly it gives connection error. please fix the issue.

**Comment by ghost** [comment]
The issue you are facing is because Rooster does not handle stream / connection management.Rooster is kind of a getting started guide on smack .If you want a proper client that takes care of all those details (that uses smack) please have a look at [xaber](https://github.com/redsolution/xabber-android) . [Conversations](https://github.com/siacs/Conversations) is another client worth a look at that takes care of these issues,(it doesn't use smack but the underlying concepts are the same.)
